-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
-- 시간 빼고 날짜만 나오도록
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
-- 연도만 확인
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;