-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE) + 1), 1) AS AVERAGE_DURATION
-- DATEDIFF = 날짜간 차이 구하기 (+1 해줘야 함) / 소수점 둘째자리에서 반올림
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION desc, CAR_ID desc